### ISSUE TITLE
calibrationFeature2 error

### ISSUE THREAD

**Issue by royfrancis** [tengmx/rnaseqcomp#1]
The documentation says

`calibrationFeature2	     Default NULL means no calibration needed.`

but when I use `calibrationFeature2=NULL` or `calibrationFeature2=rep(NULL,nrow(simdata$quant$rsem))`, I get the following error:

```
Error in signalCalibrate(simdata$quant, factor(simdata$samp$condition),  : 
  The length of "calibrationFeature2" must be the same asthe row number of "quantData" matrices.
```
 I don't have any predefined housekeeping genes. Is it possible to run without housekeeping genes?

**Comment by tengmx** [comment]
Thank you for reporting this bug. I will fix it.
Yes, you can run without housekeeping genes. Just assign a vector of TRUE to *calibrationFeature2*
