### ISSUE TITLE
Versions

### ISSUE THREAD

**Issue by royfrancis** [tengmx/rnaseqcomp#2]
I was wondering what is the latest version and where it is (bioconductor or github)? The version on github seems to be 1.7.0 while the version on bioconductor is 1.6.0. But the date on the vignette on github is 21-03-2017 while on bioconductor is 24-04-2017.

**Comment by tengmx** [comment]
Sorry for the confusing. So the github version is synchronized with the biocondctor-devel version.
In bioconductor, every package has both current release version (1.6.0 for rnaseqcomp) and devel version (1.7.0).  The 1.6.0 and 1.7.0 are actually the same content.
